// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

package store

type MockStore struct{}

func (m *MockStore) Fetch(id string) (string, error) {
	return "", nil
}

func (m *MockStore) Save(id string, value string) error {
	return nil
}
